"""init tables

Revision ID: 909daea3978c
Revises: 
Create Date: 2023-05-21 20:02:51.001831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909daea3978c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorys_vacation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__categorys_vacation'))
    )
    op.create_table('job_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=20), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__job_title'))
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('DOB', sa.Date(), nullable=False),
    sa.Column('disability', sa.Boolean(), nullable=False),
    sa.Column('child', sa.Boolean(), nullable=False),
    sa.Column('retiree', sa.Boolean(), nullable=False),
    sa.Column('job_title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title.id'], name=op.f('fk__employee__job_title_id__job_title')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__employee'))
    )
    op.create_index(op.f('ix__employee__job_title_id'), 'employee', ['job_title_id'], unique=False)
    op.create_table('former_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('job_title', sa.String(length=20), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk__former_job__employee_id__employee')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__former_job'))
    )
    op.create_index(op.f('ix__former_job__employee_id'), 'former_job', ['employee_id'], unique=False)
    op.create_table('vacation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_from', sa.Date(), nullable=False),
    sa.Column('data_to', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('categorys_vacation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorys_vacation_id'], ['categorys_vacation.id'], name=op.f('fk__vacation__categorys_vacation_id__categorys_vacation')),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk__vacation__employee_id__employee')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__vacation'))
    )
    op.create_index(op.f('ix__vacation__categorys_vacation_id'), 'vacation', ['categorys_vacation_id'], unique=False)
    op.create_index(op.f('ix__vacation__employee_id'), 'vacation', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__vacation__employee_id'), table_name='vacation')
    op.drop_index(op.f('ix__vacation__categorys_vacation_id'), table_name='vacation')
    op.drop_table('vacation')
    op.drop_index(op.f('ix__former_job__employee_id'), table_name='former_job')
    op.drop_table('former_job')
    op.drop_index(op.f('ix__employee__job_title_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_table('job_title')
    op.drop_table('categorys_vacation')
    # ### end Alembic commands ###
